#+TITLE:
#+AUTHOR:
#+DATE:
#+DESCRIPTION: Brian Peck's Resume
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   author:nil creator:nil timestamp:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_HEADER: \usepackage{fullpage}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[scaled]{helvet}
#+LATEX_HEADER: \renewcommand*\familydefault{\sfdefault}}

#+BEGIN_CENTER
#+LaTeX: {\huge Brian Peck} \\
12517 Heatherton Court #110 | San Diego, CA | 619-800-8774 | brian.andrew.peck@gmail.com
-----
#+END_CENTER

* Experience
** Software Engineer, Lockheed Martin Advanced Technologies, 2007 - Present
*** Systems Biology Simulation Framework
   - Lead developer for a Scala-based network modeling framework for the National Institutes of Health(NIH). Responsible for the development and maintenance of algorithms and user interfaces to allow biologists to model genetic reactions. Utilized SBT for build structure, and ScalaScriptEngine for run time compilation of user built networks.
*** Distributed Event Log Aggregator
   - Lead developer for a Java-based, security log aggregation and auditing tool for use across secure networks. Developed a user friendly tool for the locating and querying of logs across a network, as well as logic performed on the data for auditing. Allowed for client and server side filtering, and search capabilities. Integrated with OS independent tools to allow for use on networks with current and legacy systems. 
*** RESTfull Web Services allowing Command and Control for Office of Naval Research
   - Developed JavaScript web clients and Jersey REST services for ONR Command and Control (C2) capabilities, facilitating planning and organizational briefings to Navy Admirals. Responsible for creation of command relationship tool and web services for providing XML and JSON data to other C2 applications. Provided quality control and cross browser debugging support for off-site team members.
*** Augmented Reality Prototyping for DARPA ULTRA-Vis
   - Developed prototype of a wearable, P2P, augmented reality system to enhance the warfighter's situational awareness. Developed P2P communication systems and integrated a head-mounted display with cameras creating a 3D model of the current viewable area and directional sensors from five partners to allow functionality in and out of GPS challenged environments. Successful field demonstration to DARPA personnel in January 2010.
*** Test Automation Framework
   - Developed a Python-based test automation framework to allow for a faster testing cycle. Responsible for creation of framework and examples to allow developers to automate procedure based testing of project functionality. Improved testing cycles from minutes down to seconds. Presented a workshop on the framework, which was then adopted by team and used for two years until project completion.
** Web Development Intern, USGS Astrogeology, 2006 - 2007
   - Developed and maintained websites for the USGS Astrogeology department using JavaScript, HTML, and Perl. Updated and expanded content, and added new functionality to allow for astrogeologists to more easily view and interact with NASA imagery via mapaplanet.org. Integrated Perl scripts with GIS enabled databases to provide on demand content to users. 
* Technical Expertise
** Languages
  - Proficient in Java and Scala
  - Significant experience in JavaScript, HTML, CSS, Python, and Perl
** Tools
  - SBT, Ant, Git, Mercurial, Eclipse, IntelliJ
** Platforms
  - Windows, Linux
* Awards
  - 2011: Lockheed Martin Spot Award for exceeding project expectations on security log aggregation tool.
  - 2010: Lockheed Martin Spot Award for recognition of customer praise in creating C2 organizational tool, and technical support.
  - 2008: Lockheed Martin Spot Award for demonstrating exceptional performance developing web enabled track fusion capabilities.
  - 2008: Lockheed Martin Team Special Recognition Award for work in Java web services.
* Education
  - /Master of Science in Computer Science/, University Southern California 2013 (expected)
  - /Bachelor of Science in Computer Science/, Northern Arizona University 2007
