#+TITLE:
#+AUTHOR:
#+DATE:
#+DESCRIPTION: Brian Peck's Resume
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   author:nil creator:nil timestamp:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_HEADER: \usepackage{fullpage}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[scaled]{helvet}
#+LATEX_HEADER: \renewcommand*\familydefault{\sfdefault}}

#+BEGIN_CENTER
#+LaTeX: {\huge Brian Peck} \\
12517 Heatherton Court #110 | San Diego, CA | 619-800-8774 | brian.andrew.peck@gmail.com
-----
#+END_CENTER

* Experience
** Software Engineer, Lockheed Martin Advanced Technologies, 2007 - Present
   - Currently updating and continuing work on a scala framework used for modeling gene networks for the National Institude of Health.
   - Developed Java solutions for auditing and archiving Windows security logs across secure networks.
   - Developed developing Java adaptations of game theoretic algorithms to support mission planning, monitoring and assessment with emphasis on adversaries and deceptive reasoning for military operations.
   - Developed JavaScript web clients and Jersey web services for the Office of Naval Research. Provided on-site installation and support for the team when deploying our product and gathered customer feedback to update the team.
   - Prototyped a wearable, networked augmented reality system to enhance situational awareness for dismounted warfighters.  Developed sensor alignment algorithms and integrated hardware and software components from five partners; successfully demonstrated in the field to DARPA personnel in January 2010.
   - Developed a Python-based framework for automating testing procedures.
   - Developed prototype Android application for unmanned vehicle inventory interaction.
   - Developed a dynamically allocating ActiveMQ broker, using RabbitMQ, in early Cloud Computing research exploring scalability of known messaging implementations.
   - Developed a program to parse legacy system log files and create a Hibernate database containing the information.
   - Developed integration code connecting PostGIS databases to a JSF web client to facilitate web enabled track fusion. Provided on-site installation and product presentation to the customer.
** Web Development Intern, USGS Astrogeology, 2006 - 2007
   - Developed and updated websites for the USGS Astrogeology department including astrogeology.usgs.gov and mapaplanet.org using JavaScript, HTML, Perl, Postgres and GIS databases.
* Awards
  - 2011: Lockheed Martin Individual Spot Award in recognition of exceeding project expectations resulting in additional project funding kept on-site.
  - 2010: Lockheed Martin Individual Spot Award in recognition of customer praise for technical support across numerous product releases.
  - 2008: Lockheed Martin Individual Spot Award for exceeding expectations and demonstrating exceptional performance.
  - 2008: Lockheed Martin Team Special Recognition Award for exceeding expectations and demonstrating exceptional performance.
* Education
  - /Master of Science in Computer Science/, USC 2013 (expected)
  - /Bachelor of Science in Computer Science/, Northern Arizona University 2007
* Technical Proficiencies
  - Java: Over four years of object-oriented programming experience using Java EE (JBoss, Glassfish).
  - JavaScript: Over a year of experience developing web applications using JavaScript(YUI), HTML, CSS and GWT.
  - Linux: Over a year of Linux system administration and development experience.
  - Scala: Scala development creating a domain specific language for mathematical equations, and updating scala frameworks and libraries used for kinetic modeling.
  - Python: Significant experience developing a Python-based automated testing framework.
