#+TITLE:
#+AUTHOR:
#+DATE:
#+DESCRIPTION: Brian Peck's Resume
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   author:nil creator:nil timestamp:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_HEADER: \usepackage{fullpage}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[scaled]{helvet}
#+LATEX_HEADER: \renewcommand*\familydefault{\sfdefault}}

#+BEGIN_CENTER
#+LaTeX: {\huge Brian Peck} \\
12517 Heatherton Court #110 | San Diego, CA | 619-800-8774 | brian.andrew.peck@gmail.com
-----
#+END_CENTER

* Experience
** Software Engineer, Lockheed Martin Advanced Technologies, 2007 - Present
   - Working in Scala to provide a biologist-friendly network modeling tool for the National Institutes of Health which is currently in alpha testing.
   - Created a Java solution for auditing and archiving of Windows security logs across secure networks for internal systems administrators.
   - Developed Javascript web clients, Java back end services, and Jersey web services for use by the Office of Naval Research for Navy Admiral briefings.  Was customer face of product; provided active support reporting customer feedback to developers, and provided developers on-site debugging information in the production environment.
   - Prototyped a wearable, networked augmented reality system to enhance situational awareness for dismounted warfighters.  Developed sensor alignment algorithms and integrated hardware and software components from five partners; successfully demonstrated in the field to DARPA personnel in January 2010.
   - Developed prototype Android application for unmanned vehicle inventory interaction.
   - Developed a Python-based testing framework for automating testing procedures; framework was used for two years until project completion. 
   - Created a multi-language (Python & Java), dynamically allocating resource cloud using the RabbitMQ implementation of AMQP.
   - Developed a prototype web enabled track fusion application for the Air Force using JSF to communicate to a Java backend with a Postgres database using GIS extensions. Provided on-site installations and product presentations.
** Web Development Intern, USGS Astrogeology, 2006 - 2007
   - Developed and maintained websites for the USGS Astrogeology department including astrogeology.usgs.gov and mapaplanet.org using JavaScript, HTML, and Perl, in conjunction with Postgres and GIS databases.
* Technical Proficiencies
  - Java: Five years of Java object-oriented programming experience.
  - Scala: Significant experience developing Scala applications.
  - SBT: Experience with creating and maintaining SBT projects across multiple versions.
  - Git/Mercurial/SVN: Significant experience with version control systems, including setting up a Gitolite server to provide site wide Git access.
  - JavaScript/GWT/HTML: A year of experience developing web applications using JavaScript(YUI), HTML, CSS and GWT.
  - Linux: A year of Linux system administration and development experience.
  - Python: Experience developing a Python-based automated testing framework.
* Awards
  - 2011: Lockheed Martin Individual Spot Award in recognition of exceeding project expectations resulting in additional project funding kept on-site.
  - 2010: Lockheed Martin Individual Spot Award in recognition of customer praise for technical support across numerous product releases.
  - 2008: Lockheed Martin Individual Spot Award for exceeding expectations and demonstrating exceptional performance.
  - 2008: Lockheed Martin Team Special Recognition Award for exceeding expectations and demonstrating exceptional performance.
* Education
  - /Master of Science in Computer Science/, USC 2013 (expected)
  - /Bachelor of Science in Computer Science/, Northern Arizona University 2007
